export const UPDATE_STATE = "UPDATE_STATE";
export const UPDATE_CITIES = "UPDATE_CITIES";
export const UPDATE_CITIES_LOCATION = "UPDATE_CITIES_LOCATION";
export const SET_ZOOM_LEVEL = "SET_ZOOM_LEVEL";
export const SET_MAP_CENTER = "SET_MAP_CENTER";
